apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-test-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "helm-test-app.labels" . | nindent 4 }}
type: Opaque
data:
  pass: {{ .Values.secrets.data.pass }}
  client_id: {{ .Values.secrets.data.client_id }}
