apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-test-app.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "helm-test-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helm-test-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
