apiVersion: v1
entries:
  helm-test-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-30T17:50:56.627377+05:30"
    description: A Helm chart for deploying a bun application on Kubernetes
    digest: 251848fe184d08203f2c1c1eb23ccd050fbde5c824635369b190b55cc18790c2
    keywords:
    - nodejs
    - application
    maintainers:
    - email: mayur@scogo.ai
      name: meru45
    name: helm-test-app
    type: application
    urls:
    - https://meru45.github.io/Test-Helm-Chart/helm-test-app-1.0.0.tgz
    version: 1.0.0
generated: "2025-12-30T17:50:56.623064+05:30"
