apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-test-app.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "helm-test-app.labels" . | nindent 4 }}
data:
  node_env: {{ .Values.env | default "dev" | quote }}
  port: {{ .Values.configmap.data.port | default "4000" | quote }}
  user_name: {{ .Values.configmap.data.user_name | default "meru45" | quote }}
  email: {{ .Values.configmap.data.email | default "name@example.com" | quote }}
